<?php

/**
 * @file
 * Contains dap_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dap_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dap_custom module.
    case 'help.page.dap_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom tweaks for the Delphi Auto Parts website.') . '</p>';
      return $output;

    default:
  }
}
